### ISSUE TITLE
Consider making Parcel optional

### ISSUE THREAD

**Issue by jamesopstad** [pikapkg/create-snowpack-app#39]
Following on from the discussion in #29, I wonder what you would think about making installing Parcel optional? The dev environment in Snowpack V2 is brilliant and personally I think getting people set up with that as quickly and painlessly as possible should be the priority. Parcel installs a huge amount of dependencies (107.3 MB) and many users will still choose to use Webpack or Rollup to build for production. Snowpack-react-app isn't much lighter than create-react-app at the moment but would be much smaller if production bundling wasn't included by default. A script to add Parcel to an existing project would be great.

**Comment by FredKSchott** [comment]
yea you're right, I just checked Parcel 2 and it installs even more by default (`396.9 MB`). /cc @devongovett just a heads up in case that's a surprise to hear, I know how how these things can sneak up.

Having bundling being optional (but reccomended) for production has always been the goal. Let me see what's left to tackle there since I don't believe it would work out of the box today.

**Comment by FredKSchott** [comment]
Was able to make optional again, thanks to our HMR/proxy work done today in dev mode!

New default behavior:

<img width="718" alt="Screen Shot 2020-05-09 at 10 20 51 PM" src="https://user-images.githubusercontent.com/622227/81491542-78c79a80-9244-11ea-90d3-703b0fd5d866.png">
