### ISSUE TITLE
The Vue template fails

### ISSUE THREAD

**Issue by yannbertrand** [pikapkg/create-snowpack-app#5]
Running `yarn start` on the Vue template give a blank page and this error on Chrome devtools:

![image](https://user-images.githubusercontent.com/5855339/81122816-0a2bc980-8f32-11ea-9350-62760375b7e0.png)

`yarn build` gives another error:
![image](https://user-images.githubusercontent.com/5855339/81123139-a655d080-8f32-11ea-9f85-4df6d78f19df.png)

Env: macOS Catalina, node@14

**Comment by agneym** [comment]
Put in a PR to fix this. You can run `npm install vue@next` in the mean time to get rid of this error.

**Comment by FredKSchott** [comment]
So we have two choices:

1. Keep vue 3 and remove test running from the template until vue-jest is updated to support vue 3.
2. Downgrade "plugin:vue" to use the vue 2 compiler instead of the vue 3 compiler.

I really want to support test running, but at this point I'd rather we focus on making the vue 3 plugin as great as possible in anticipation of their release + vue 3 testing support.

**Comment by Akanoa** [comment]
Hello,

I've the same issue with the `blank` preset

I've launched 
```
npx snowpack build --bundle
cd build && npx http-server
```

That leads to this error
<img width="783" alt="Capture d’écran 2020-05-06 à 16 14 16" src="https://user-images.githubusercontent.com/4521637/81187992-10af5500-8fb5-11ea-9595-2eff0ebee395.png">

I hope it could help you :)

**Comment by FredKSchott** [comment]
- Fixed the issue by removing the test runner for now, until Vue 3 has proper testing.
- Added a note to the README that this is for Vue 3 only.

@Akanoa I can't reproduce with the default blank template, can you try re-running in case it's an outdated issue? If you still see it, feel free to file a new issue and I'll help debug

**Comment by kjugi** [comment]
Downgrading the `plugin:vue` to use `vue-template-compiler` for compile vue2 files is not enough. It leads us to the next problem with export in our files. 

`The requested module 'yourFile' does not provide an export named 'default'`

So I assume that snowpack and vue2.x aren't compatible in any way.

**Comment by FredKSchott** [comment]
Yea, I don't think it's a 1:1 replacement unfortunately. We don't have the bandwidth to invest in vue 2 given vue 3's imminent release, but would certainly love to point developers to a vue 2 community plugin if anyone wants to build one (feel free to copy & modify `@snowpack/plugin-vue` as much as you need if that helps).

**Comment by RecuencoJones** [comment]
@FredKSchott I've created [a sample repository](https://github.com/RecuencoJones/snowpack-plugin-vue-2) for vue 2 plugin – did copy existing plugin and tweaked a bit checking how vue-loader works.

I'm not sure it will work 100% but I'll be testing some basic use cases of Vue SFCs and plugins.

**Comment by FredKSchott** [comment]
I believe vue 3 is more or less able to run via vue 2 code, so I'm happy to hear this!

**Comment by miljan-aleksic** [comment]
I honestly don't understand why would Snowpack officially support Vue 3, a version that is not even yet stable, instead of supporting Vue 2 which is a version that will still be used for a long period even after Vue 3 stable release. Seems Snowpack aims to simplify the dev process of the future, not the present :(

That said, don't take my feedback the wrong way, I appreciate all the effort ;)

**Comment by FredKSchott** [comment]
Purely because Vue 3 has a new compiler, so it didn't make sense to build a plugin that would rely on a compiler that already appeared to be deprecated.

That being said, it wouldn't be too hard to create a Vue 2 build plugin, based off our existing Vue 3 plugin. You'd just need to swap out the new compiler for the old one, and you could use the existing Rollup/Webpack/Browserify Vue plugins for reference to how the Vue 2 compiler works. 

I'd be happy to provide guidance from the Snowpack side of things if anyone wanted to take a stab at this, seems like a lot of people would find it useful!
